import shutil
import os

source_dir = "/home/yogipatel/Documents/UK-Grid-instability/Final Report/figures"
target_dir = "/home/yogipatel/Documents/UK-Grid-instability/report/figures"

os.makedirs(target_dir, exist_ok=True)

# List of conceptual figures to copy (not generated by python)
conceptual_figures = [
    "figure_3_1_system_architecture.png",
    "figure_3_2_opsda_compression.png",
    "figure_3_3_quantile_concept.png",
    "figure_1_1_frequency_safety_zone.png",
    "figure_1_2_blackout_baseline.png",
    "figure_2_1_swing_equation.png"
]

for fig in conceptual_figures:
    src = os.path.join(source_dir, fig)
    dst = os.path.join(target_dir, fig)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"Copied: {fig}")
    else:
        print(f"Skipped (not found): {fig}")
