# -*- coding: utf-8 -*-
"""data_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEhFrKMi77gzS7UudslCCrZfrU4Vs8mc
"""

!pip install polars openmeteo-requests requests-cache retry

import polars as pl
from src.data_loader import fetch_frequency_data, fetch_inertia_data, fetch_weather_data
from src import config
from src.model_trainer import train_and_evaluate_lgbm_classifier, train_quantile_model, train_lstm_model, calculate_picp_mpiw
from src.config import QUANTILE_ALPHAS, LGBM_QUANTILE_LOWER_PATH, LGBM_QUANTILE_UPPER_PATH, LGBM_MODEL_PATH, LSTM_MODEL_PATH, SCALER_PATH
import pandas as pd # OpenMeteo returns pandas-ready objects, we'll convert to Polars later
import joblib
import shutil
import os
import numpy as np # Import numpy for array manipulation
import matplotlib.pyplot as plt # Import for plotting
import shap # Import for explain_predictions

# USAGE:
# Replace with your actual downloaded file path
# df_freq = load_frequency_data("frequency_aug2019.csv")
# print(df_freq.head())

df_freq = fetch_frequency_data(
    start_date=config.WEATHER_API_DEFAULT_START_DATE, 
    end_date=config.WEATHER_API_DEFAULT_END_DATE
)
print(df_freq.head())

"""weather data"""

# USAGE:
# df_weather = fetch_weather_data("2019-08-01", "2019-08-31")
# print(df_weather.head())

df_weather = fetch_weather_data(
    config.WEATHER_API_DEFAULT_START_DATE, 
    config.WEATHER_API_DEFAULT_END_DATE
)
print(df_weather.head())

# Fetch inertia data
df_inertia = fetch_inertia_data(
    start_date=config.WEATHER_API_DEFAULT_START_DATE, 
    end_date=config.WEATHER_API_DEFAULT_END_DATE
)
print(df_inertia.head())

"""merging data"""

from src.feature_engineering import merge_datasets # Import merge_datasets from src

# USAGE:
# df_final = merge_datasets(df_freq, df_weather, df_inertia)
# print(df_final.head())

df_final = merge_datasets(df_freq, df_weather, df_inertia)
print(df_final.head())

from src.feature_engineering import create_features # Import create_features from src

# EXECUTE
df_processed = create_features(df_final)

# Inspect the new columns
print(df_processed.select([
    "timestamp", "grid_frequency", "rocof", "volatility_10s", "target_is_unstable"
]).head(10))

# Check how many unstable events we actually have in August 2019
print("\nUnstable Events Count:")
print(df_processed["target_is_unstable"].value_counts())

# EXECUTE classifier
global_model, global_X_test, global_test_polars = train_and_evaluate_lgbm_classifier(df_processed)

# EXECUTE quantile models
lower_model, X_test_quantile, y_test_quantile = train_quantile_model(df_processed, alpha=QUANTILE_ALPHAS[0])
upper_model, _, _ = train_quantile_model(df_processed, alpha=QUANTILE_ALPHAS[1]) # Only need the model, X_test and y_test are the same

# Calculate and print PICP and MPIW
print("\nEvaluating Quantile Regression Models...")
lower_predictions = lower_model.predict(X_test_quantile)
upper_predictions = upper_model.predict(X_test_quantile)

confidence_level = QUANTILE_ALPHAS[1] - QUANTILE_ALPHAS[0] # e.g., 0.9 - 0.1 = 0.8 for 80% PI
picp, mpiw = calculate_picp_mpiw(y_test_quantile, lower_predictions, upper_predictions, confidence_level)
print(f"PICP (Confidence Level {confidence_level*100:.0f}%): {picp:.4f}")
print(f"MPIW: {mpiw:.4f}")

# EXECUTE LSTM
model_lstm, global_scaler = train_lstm_model(df_processed)

def explain_predictions(model, X_test, df_test_polars):
    print("Generating Explanations (SHAP Values)...")

    # 1. Get Probabilities instead of just 0/1
    # ----------------------------------------
    # model.predict_proba returns [Prob_Stable, Prob_Unstable]
    # We want the probability of 'Unstable' (Index 1)
    y_prob = model.predict_proba(X_test)[:, 1]

    # Add probability to the test dataframe for inspection
    # We need to reconstruct the dataframe temporarily
    df_results = df_test_polars.select(["timestamp", "grid_frequency", "target_is_unstable"]).to_pandas()
    df_results["alert_probability"] = y_prob

    # 2. Inspect the "Blackout Moment" (Approx 16:52 UTC on Aug 9)
    # -----------------------------------------------------------
    print("\nTop 5 Highest Risk Moments on August 9:")
    print(df_results.sort_values("alert_probability", ascending=False).head(5))

    # 3. SHAP Analysis (Why did the model predict Unstable?)
    # ------------------------------------------------------
    # We use TreeExplainer for LightGBM
    explainer = shap.TreeExplainer(model)

    # Calculate SHAP values for a subset (calculating for all 86k rows is slow)
    # Let's pick the top 100 "highest risk" rows to understand what drives alarms
    high_risk_indices = df_results.sort_values("alert_probability", ascending=False).head(100).index
    X_for_shap = X_test.iloc[high_risk_indices]
    shap_values = explainer.shap_values(X_for_shap)

    # Ensure shap_values[1] is a 2D array (matrix) for summary_plot
    shap_values_for_plot = shap_values[1]
    if isinstance(shap_values_for_plot, list): # Check if it's a list (e.g., from multi-output explainer for binary classification)
        if len(shap_values_for_plot) == 1:
            shap_values_for_plot = shap_values_for_plot[0]
        else:
            # If it's a list of multiple arrays, and we want to plot for class 1, ensure it's still treated correctly
            # This case might not be directly applicable for binary classification where shap_values[1] is typically one array
            # For now, if it's a list with multiple elements, and we're picking index 1, assume it's the correct array.
            # If it leads to errors, further debugging of shap_values structure would be needed.
            shap_values_for_plot = shap_values_for_plot # Keep as is if it's already the desired array for class 1

    if isinstance(shap_values_for_plot, np.ndarray) and shap_values_for_plot.ndim == 1:
        # Assuming it's a flattened array of (num_samples * num_features) or (num_features,)
        # Try to reshape to (num_samples, num_features)
        if shap_values_for_plot.size == X_for_shap.shape[0] * X_for_shap.shape[1]:
            shap_values_for_plot = shap_values_for_plot.reshape(X_for_shap.shape[0], X_for_shap.shape[1])
        elif shap_values_for_plot.size == X_for_shap.shape[1]: # If it's features for a single sample
            shap_values_for_plot = shap_values_for_plot.reshape(1, -1)
        elif shap_values_for_plot.size == X_for_shap.shape[0]: # If it's a single value per sample, but needs to be 2D
            shap_values_for_plot = shap_values_for_plot.reshape(-1, 1)
        else:
            print(f"Warning: shap_values[1] has unexpected 1D shape {shap_values_for_plot.shape} that cannot be easily reshaped to 2D for plotting. Attempting to proceed with current shape, plot might fail or be incorrect.")


    # 4. PLOT: Summary Plot
    # ---------------------
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values_for_plot, X_for_shap, plot_type="bar", show=False)
    plt.title("What Drives the Alert System? (Top Risk Factors)")
    plt.show()

    return df_results

# EXECUTE
# The required variables (model, X_test, test_pl) are now returned globally from train_and_evaluate
df_results = explain_predictions(global_model, global_X_test, global_test_polars)

def export_project_files():
    print("Packaging project for Local Dashboard...")

    # Create a folder for export
    os.makedirs("export_pack", exist_ok=True)

    # 1. Save LightGBM Classifier Model
    joblib.dump(global_model, LGBM_MODEL_PATH)

    # 2. Save LightGBM Quantile Models
    joblib.dump(lower_model, LGBM_QUANTILE_LOWER_PATH)
    joblib.dump(upper_model, LGBM_QUANTILE_UPPER_PATH)

    # 3. Save LSTM Model
    # Keras models need a specific format
    # The `model_lstm` is directly available as it's returned by train_lstm_model
    model_lstm.save(LSTM_MODEL_PATH)

    # 4. Save the Scaler (CRITICAL)
    joblib.dump(global_scaler, SCALER_PATH)

    # 5. Save a "Demo Slice" of Data
    # We can't load 2.6 million rows in the dashboard easily.
    # Let's save just August 9th (The Blackout Day) for the demo.

    # Re-create the test slice
    split_date = "2019-08-09 00:00:00"
    df_demo = df_processed.filter(
        (pl.col("timestamp") >= pl.lit(split_date)) &
        (pl.col("timestamp") < pl.lit("2019-08-10 00:00:00"))
    )
    # Save as CSV
    df_demo.write_csv("export_pack/demo_data_aug9.csv")

    print("Files saved to /content/export_pack/")

    # Zip it up for easy download
    shutil.make_archive("/content/project_export", 'zip', "export_pack")
    print("Zipping complete. Download 'project_export.zip' from the Files tab!")

# EXECUTE
export_project_files()