= Findings

== Introduction

This chapter presents the objective, empirical results generated by the GridGuardian forecasting and alerting system. The evaluation focuses exclusively on the predictive outputs and explainability metrics derived directly from the LightGBM inference engine and the LSTM Monte Carlo comparator.

The August 9, 2019 UK blackout serves as the primary evaluation scenario. The analysis utilizes a strict hold-out testing set, ensuring that all findings presented herein reflect true out-of-sample generalization.

== Predictive Accuracy and Error Distribution

Before evaluating the alerting logic, the fundamental accuracy of the underlying quantile regression models must be quantified. The system is required to capture the structural trajectory of the grid frequency; however, statistical evaluation reveals that the "tightness" of the predicted bounds comes at the expense of nominal coverage reliability.

=== Residual Error and Quantile Metrics Analysis

To evaluate the LightGBM models (predicting the $alpha=0.1$ lower bound), multiple rigorous statistical metrics were calculated. Table 4 presents the primary benchmark metrics for the August 2019 dataset.

#figure(
  table(
    columns: (auto, auto, auto, auto, auto),
    align: (left, right, right, right, center),
    table.header(
      [*Metric*], [*Lower Bound ($alpha=0.1$)*], [*Upper Bound ($alpha=0.9$)*], [*Operational Target*], [*Status*]
    ),
    [Pinball Loss†], [0.0032 ± 0.0001], [0.0160 ± 0.0004], [< 0.02], [Pass],
    [Mean Absolute Error (Hz)], [0.0243 [0.0231, 0.0255]], [0.0193 [0.0183, 0.0203]], [< 0.05], [Pass],
    [Root Mean Square Error (Hz)], [0.0419 [0.0398, 0.0440]], [0.0409 [0.0389, 0.0429]], [< 0.10], [Pass],
    [PICP (%)], [73.5 [73.4, 73.6]], [—], [$>= 80%$], [Fail],
    [MPIW (Hz)], [0.0357 [0.0340, 0.0375]], [—], [< 0.20], [Pass],
  ),
  caption: [Comprehensive statistical evaluation metrics for the LightGBM quantile bounding models on the August 2019 dataset. †Pre-recalibration Pinball Loss = 0.0032. The post-recalibration value of 0.0012 is reported in Table 7 (Summer column) as part of the seasonal evaluation, which also reflects isotonic-adjusted bounds. ‡Bootstrap confidence intervals (B=1,000 resamples) computed over the full August 2019 test set. PICP bounds computed using the Wilson score interval.]
)

The Mean Absolute Error (MAE) of 0.0243 Hz indicates that the model follows the general grid frequency within a 25mHz margin. However, the Prediction Interval Coverage Probability (PICP) achieved only 73.5%. This indicates that the model's physical boundary predictions are statistically overconfident, failing the strict 80% coverage criterion. This result suggests that while the tree-based architecture is computationally efficient, it exhibits an "interval collapse" during periods of high volatility, where the predicted bounds fail to encapsulate the true frequency nadir with sufficient regularity for safety-critical deployment.

#figure(
  image("../figures/figure_4_4_residual_analysis.png", width: 90%),
  caption: [Residual distributions for the LightGBM models. The Mean Absolute Error (MAE) of 0.0243 Hz represents the realistic performance ceiling of the current prototype.]
)

=== Classification Performance Metrics

Because the continuous quantile bounds are heuristically converted into a binary `target_is_unstable` alert, classification metrics can be evaluated on the hold-out set containing the August 2019 blackout (Table 5).

#figure(
  table(
    columns: (1.5fr, 1fr, 1fr),
    align: left,
    [*Metric*], [*Value*], [*95% Confidence Interval*],
    [Recall (Sensitivity)], [99.2%], [[98.5%, 99.7%]],
    [Precision], [94.1%], [[92.8%, 95.3%]],
    [F1-Score], [96.6%], [[95.6%, 97.4%]],
    [ROC-AUC], [0.998], [[0.996, 0.999]]
  ),
  caption: [Binary classification performance metrics for the heuristic alert system on the August 2019 test set ($N=3,600$ unstable events out of approximately 2.6 million total records, representing a local imbalance of ~722:1 during the high-volatility validation period).]
)

The system achieves a 99.2% recall rate on a test set containing 3,600 verified unstable events (defined by the physical heuristic bounds). This statistically significant sample size confirms the system's robust sensitivity to structural failure. The accompanying precision of 94.1% indicates a low false-positive rate, crucial for avoiding "alarm fatigue" in operational control rooms. In this safety-critical context, the more diagnostically meaningful metric is Recall, which directly quantifies the system's ability to minimize catastrophic missed alerts. However, as Section 4.5 demonstrates, high statistical recall on hold-out data does not necessarily translate into a predictive lead-time advantage during catastrophic transients.

== Feature Importance: Validating the Physics Integration

The core hypothesis of this research is that machine learning models for power systems must rely on structural physical metrics rather than memorizing stochastic sensor noise. The global feature importance of the LightGBM model validates this approach.

=== Structural Dominance

#figure(
  image("../figures/figure_4_2_feature_importance.png", width: 90%),
  caption: [Global feature importance for the LightGBM inference engine, highlighting the dominance of physics-based momentum indicators over raw environmental context.]
)

The global feature importance analysis reveals a critical insight into the model's decision-making hierarchy. As illustrated in Figure 3, short-term frequency derivatives (`rocof_1s` at 15.4%) and the absolute grid frequency (9.4%) overwhelmingly dominate the decision splits. In contrast, contextual features such as the OpSDA Wind Ramp Rate and Renewable Penetration exhibit near-zero split-count importance. This finding suggests that for sub-second transient instability prediction, the model prioritizes high-fidelity temporal momentum signals over slower-moving environmental or energy-mix data. This prioritization validates the system's design as a transient protection mechanism, where the primacy of immediate physical derivatives outweighs the predictive utility of macro-scale meteorological trends.

== Probabilistic Forecasting Reliability

The operational utility of GridGuardian depends on whether its stated risk probabilities align with empirical observation. 

=== Isotonic Recalibration Performance

The recalibrated PICP result of 73.5% still represents a failure of the 80% threshold even after recalibration.

#figure(
  image("../figures/figure_5_4_calibration_reliability.png", width: 90%),
  caption: [Calibration reliability diagrams demonstrating the alignment of forecasted probability quantiles with empirical observation frequencies.]
)

The calibration analysis (Figure 4) reveals that prior to post-hoc adjustment, the raw model exhibited a significant bias. The application of Isotonic Regression attempts to remap these probabilities; however, the persistent 73.5% PICP failure suggests that recalibration alone cannot compensate for the model’s structural inability to capture the most extreme tail-risk events. While the bounds are "trustworthy" for 73% of observations, they do not yet satisfy the legal requirements for automated EFR intervention without a wider safety margin.

== Forensic AI (XAI) and The August Blackout Reconstruction

The definitive evaluation of the system is its response to the August 9, 2019 blackout. Rather than a "predictive warning," the system's performance is better characterized as a *high-fidelity forensic reconstruction* of the collapse.

=== The Fragility Fingerprint: Reactive Identification

#figure(
  image("../figures/impressive_uncertainty_ribbon.png", width: 95%),
  caption: [Raw frequency time-series of the August 2019 blackout event overlaid with the LightGBM predicted quantile boundaries, illustrating the reactive alert identification and quantile bound behaviour during the collapse.]
)

#figure(
  table(
    columns: (auto, auto, auto, auto, auto),
    align: (left, center, center, center, left),
    table.header(
      [*Signal Feature*], [*12:00:00 (Stable Noon)*], [*15:52:36 (Pre-Collapse)*], [*15:53:49 (Nadir)*], [*Physical Interpretation*]
    ),
    [RoCoF Severity Alert], [OFF], [*ON*], [*ON*], [Detects initial sudden momentum drop],
    [RoCoF Acceleration Alert], [OFF], [*ON*], [*ON*], [Detects violent non-linear collapse],
    [10s Volatility Alert], [OFF], [OFF], [*ON*], [Detects severe post-fault oscillations],
    [Low Inertia Vulnerability], [OFF], [*ON*], [*ON*], [Flags insufficient grid momentum],
    [LGBM Quantile Risk ($>35%$)], [OFF], [OFF], [*ON*], [Lower quantile bound statistically breached],
  ),
  caption: [Signal state analysis tracing the multi-physics 'Fragility Fingerprint' during the August 9, 2019 blackout.]
)

As documented in Table 6, the 'Fragility Fingerprint' was successfully activated during the fault window. However, the primary alert trigger occurred at *15:54:04 UTC*. Given that the frequency nadir (the point of maximum instability) occurred at *15:53:49 UTC*, this trigger represents a *reactive identification* of the failure rather than a predictive warning (Table 5). The system provided a 15-second "post-nadir" forensic confirmation. While this is operationally useful for automated incident reporting, it fails to meet the 1.0-second predictive lead-time required for EFR battery deployment during this specific catastrophic event.

=== SHAP Waterfall Decomposition

#figure(
  image("../figures/figure_5_2_shap_waterfall.png", width: 85%),
  caption: [SHAP Waterfall decomposition for the reactive alert at 15:54:04 UTC. The model identifies extreme RoCoF as the primary driver, confirming physical consistency but highlighting the lack of predictive "early-warning" indicators.]
)

The SHAP waterfall (Figure 6) confirms that at 15:54:04, the model's logic was dominated by immediate 1s RoCoF and frequency deviation. The lack of predictive success is likely attributable to the model's reliance on these high-speed derivatives, which only manifest *after* the initial physical disconnect has occurred. This suggests that for future iterations, the model requires features capable of detecting the pre-fault loss of synchronous momentum prior to the visible frequency drop. This level of granular explainability satisfies the transparency requirements for engineering audits, even when the system fails its primary predictive objective.
