= Conclusion

== Summary of Technical Contributions and Hypotheses Resolution

This research concludes that while a physics-informed, tree-based machine learning architecture offers a computationally efficient and interpretable engine for grid monitoring, it failed to meet the rigorous reliability and lead-time benchmarks required for autonomous grid protection. Despite the implementation of a high-speed inference pipeline ($<0.20$s) and the successful extraction of domain-specific features (RoCoF, OpSDA), the prototype achieved a Prediction Interval Coverage Probability (PICP) of only 73.5% on the primary August 2019 test set (Table 4)—falling short of the 80% operational safety target.

Forensic reconstruction of the August 9, 2019 blackout event revealed that the system functioned as a reactive identifier rather than a predictive early-warning asset, with the primary alert trigger occurring 15 seconds post-nadir (15:54:04 UTC). The available evidence is therefore insufficient to support $H_1$: the prototype failed to meet both the 80% PICP criterion and the 1.0-second lead-time criterion during the severe blackout event available for evaluation. $H_1$ therefore cannot be accepted on the basis of the evidence presented.

The Null Hypothesis ($H_0$) is resolved in two distinct dimensions. First, $H_0$ is rejected with respect to the latency and recall comparison: the hybrid LightGBM architecture significantly outperforms the LSTM baseline, achieving a sub-second inference latency of < 0.20 seconds and a recall rate of 99.2% (Table 5), confirming that physics-informed feature engineering yields a structural advantage for time-critical alerting. Second, $H_0$ is not rejected with respect to industrial safety reliability: the observed PICP of 73.5% (Table 4)—falling below the 80% target—and the confirmed reactive rather than predictive behavior during the August 2019 nadir validate $H_0$'s claim that the current pipeline cannot consistently meet safety targets across diverse grid conditions. This dual resolution demonstrates that the GridGuardian prototype represents a meaningful engineering advance over purely reactive baselines, while simultaneously establishing the calibration and generalization benchmarks that must be addressed before operational deployment.

The hybrid architecture successfully achieved a 99.2% recall rate on the hold-out test set while maintaining a 0.20-second inference latency, significantly outperforming the deeper LSTM baseline (1.45s). However, the coverage failure indicates that the model's uncertainty estimates were overconfident during the transient blackout window. Global SHAP analysis confirmed that the model correctly prioritized short-term frequency derivatives (`rocof_1s`) over raw environmental noise, validating the physics-informed design even where the strict statistical reliability thresholds were not met. The results suggest that the "decision window" for automated grid response remains a formidable engineering challenge that requires further reconciliation between algorithmic speed and statistical coverage.

== Professional Reflection

Developing GridGuardian was a transition from textbook theory to the reality of engineering a safety-critical pipeline. One of the biggest technical hurdles was managing the high-resolution frequency data. I initially tried using Pandas, but the memory overhead and performance issues during the temporal alignment of 1-second telemetry data caused constant crashes. This pushed me to learn and implement a high-performance Polars pipeline. The switch to Polars and the use of its `join_asof` function not only solved the performance bottleneck but taught me the value of choosing the right tool for large-scale data engineering. 

Beyond the code, the most humbling part of the project was admitting that my model failed to meet its 80% reliability target. In university coursework, you often focus on achieving the highest accuracy, but this project showed me that in the real world—especially in national infrastructure—admitting a model's limitations is as important as achieving a headline metric. This experience has shifted my perspective from being a student to an engineer who understands that transparency and reliability are critical for safety-critical systems.

Ultimately, the development and evaluation of GridGuardian identify the 'performance ceiling' of current ensemble-based grid AI when constrained to 1Hz telemetry. This research contributes a fully implemented software framework, a causal data-merging pipeline, and a forensic auditing methodology to the field of power system security. By documenting the exact failure modes and calibration drift of the prototype, this work provides the empirical foundation required to bridge the gap between theoretical machine learning and the safety requirements of national infrastructure. The project serves as a case study in the practical constraints of physics-informed design, demonstrating that while algorithms can be engineered for speed, operational integrity cannot be compromised by coverage failures — a tension that must be resolved before ensemble methods can be responsibly deployed.
