= Conclusion

== Summary of Technical Contributions and Hypotheses Resolution

This research concludes that while a physics-informed, tree-based machine learning architecture offers a computationally efficient and interpretable engine for grid monitoring, it failed to meet the rigorous reliability and lead-time benchmarks required for autonomous grid protection. Despite the implementation of a high-speed inference pipeline ($<0.20$s) and the successful extraction of domain-specific features (RoCoF, OpSDA), the prototype achieved a Prediction Interval Coverage Probability (PICP) of only 73.5% on the primary August 2019 test set (Table 4)—falling short of the 80% statutory safety target.

Forensic reconstruction of the August 9, 2019 blackout event revealed that the system functioned as a reactive identifier rather than a predictive early-warning asset, with the primary alert trigger occurring 15 seconds post-nadir (15:54:04 UTC). The available evidence is therefore insufficient to support $H_1$: the prototype failed to meet both the 80% PICP criterion and the 1.0-second lead-time criterion during the sole catastrophic discontinuous event available for evaluation. $H_1$ therefore cannot be accepted on the basis of the evidence presented.

The Null Hypothesis ($H_0$) is resolved in two distinct dimensions. First, $H_0$ is rejected with respect to the latency and recall comparison: the hybrid LightGBM architecture demonstrably and significantly outperforms the LSTM baseline, achieving a sub-second inference latency of < 0.20 seconds and a recall rate of 99.2% (Table 5), confirming that physics-informed feature engineering yields a structural advantage for time-critical alerting. Second, $H_0$ is not rejected with respect to industrial safety reliability: the observed PICP of 73.5% (Table 4)—falling below the 80% statutory threshold—and the confirmed reactive rather than predictive behavior during the August 2019 nadir empirically validate $H_0$'s claim that the current pipeline cannot consistently meet industrial safety targets across diverse grid conditions. This dual resolution demonstrates that the GridGuardian prototype represents a meaningful engineering advance over purely reactive baselines, while simultaneously establishing the calibration and generalization benchmarks that must be addressed before operational deployment.

The hybrid architecture successfully achieved a 99.2% recall rate on the hold-out test set while maintaining a 0.20-second inference latency, significantly outperforming the deeper LSTM baseline (1.45s). However, the coverage failure indicates that the model's uncertainty estimates were overconfident during the transient blackout window. Global SHAP analysis confirmed that the model correctly prioritized short-term frequency derivatives (`rocof_1s`) over raw environmental noise, validating the physics-informed design even where the strict statistical reliability thresholds were not met. The results suggest that the "decision window" for automated grid response remains a formidable engineering challenge that requires further reconciliation between algorithmic speed and statistical coverage.

== Professional Reflection

The development of GridGuardian represented a profound period of professional maturation, transitioning from theoretical university coursework to engineering a safety-critical, end-to-end software pipeline. Operating at the intersection of power system physics and advanced data science exposed the severe realities of applied machine learning. Overcoming the initial challenges of asynchronous data leakage through the implementation of Polars `join_asof`, and enforcing strict chronological integrity, instilled a permanent respect for robust data engineering in time-series forecasting.

Practically, this dissertation served as an intensive exercise in applied software engineering. Managing the project via Agile sprints, maintaining Git version control, and writing object-oriented Python to execute the Swinging Door Algorithm (OpSDA) shifted my operational mindset to that of a professional engineer. Furthermore, the process of implementing and validating quantile regression and Bayesian uncertainty quantification in a safety-critical engineering context revealed the substantial gap between theoretical model formulation and production-ready deployment requirements. The GridGuardian project has permanently equipped me with the technical discipline, resilience, and analytical rigor required to succeed in the industrial data science sector.

Ultimately, the development and evaluation of GridGuardian identify the 'performance ceiling' of current ensemble-based grid AI when constrained to 1Hz telemetry. This research contributes a fully implemented software framework, a causal data-merging pipeline, and a rigorous forensic auditing methodology to the field of power system security. By documenting the exact failure modes and calibration drift of the prototype, this work provides the empirical foundation required to bridge the gap between theoretical machine learning and the uncompromising safety requirements of national infrastructure. The project serves as an empirical case study in the practical constraints of physics-informed design, demonstrating that while algorithms can be engineered for extreme speed, operational integrity cannot be compromised by statistical coverage failures — a tension that must be resolved before ensemble methods can be responsibly deployed in safety-critical national infrastructure.
